
[[_standalone-ha-mode]]

=== Clustered Mode

Clustered operation mode is for when you want to run {project_name} within a cluster.  This mode
requires that you have a copy of the {project_name} distribution on each machine you want to run a server instance.
This mode is very easy to deploy, and require a few configuration cahnge.

==== Recommended Network Architecture

The recommended network architecture for deploying Aerobase is to set up an HTTP/HTTPS load balancer on a public IP 
address that routes requests to Aerobase servers sitting on a private network. 
This isolates all clustering connections and provides a nice means of protecting the servers.

==== Clustered Configuration

The distribution has a mostly pre-configured app server configuration file for running within a cluster.  It has all the specific
infrastructure settings for networking, databases, caches, and discovery.  This file resides
in _/etc/aerobase/aerobase.rb_.  There's a few things missing from this configuration.
You can't run {project_name} in a cluster without configuring a shared database connection.  You also need to
deploy some type of load balancer in front of the cluster.  The <<_clustering,clustering>> and
<<_database,database>> sections of this guide walk you though these things.

.Cluster Config
.cat aerobase.rb
[source,ruby,subs="attributes+"]
----
global['contactpoints'] = 'HOST1, HOST2'
...
aerobase_server['server_address'] = node['ipaddress'] 
----

WARNING: Any changes you make to this file while the server is running will not take effect.
      When using host names as 'contactpoints', make sure hostname is resolved to a network address.
      See the link:{appserver_admindoc_link}[_{appserver_admindoc_name}_] for more information.

==== Clustered Boot Script

You use the same boot scripts to start {project_name} as you do in standalone mode.

To boot the server:

.Linux/Unix
[source]
----
$ aerobase-ctl start
----

.Windows
[source]
----
> aerobase-ctl.bat start
----
