
=== Enable HTTPS

The Nginx config will tell browsers and clients to only communicate with your {project_name} instance over a secure connection for the next 24 months. 
By enabling HTTPS you'll need to provide a secure connection to your instance for at least the next 24 months. 
By default, {project_name} does not use HTTPS. If you want to enable HTTPS for `aerobase.example.com`, add the following statement to `/etc/aerobase/aerobase.rb`:

[source,ruby,subs="attributes+"]
----
# note the 'https' below
external_url "https://aerobase.example.com"
----

Because the hostname in our example is 'aerobase.example.com', aerobase will look for key and certificate files called 
`/etc/aerobase/ssl/aerobase.example.com.key` and  `/etc/aerobase/ssl/aerobase.example.com.crt` respectively. 
Create the /etc/aerobase/ssl directory and copy your key and certificate there.

[source,bash,subs="attributes+"]
----
sudo mkdir -p /etc/aerobase/ssl
sudo chmod 700 /etc/aerobase/ssl
sudo cp aerobase.example.com.key aerobase.example.com.crt /etc/aerobase/ssl/
----

For self-signed certificate, we can create the SSL key and certificate files in one motion by typing:
[source,bash,subs="attributes+"]
----
sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/aerobase/ssl/aerobase.example.com.key -out /etc/aerobase/ssl/aerobase.example.com.crt    
----
